[build]
  command = "npm run build"
  publish = "dist/frontend-capstone"
  environment = { NPM_FLAGS = "--legacy-peer-deps" }

[build.environment]
  NPM_FLAGS = "--legacy-peer-deps"

[context.production.environment]
  NPM_FLAGS = "--legacy-peer-deps"
